### ISSUE TITLE
Update support for the single RGB LED for Home Assistant

### ISSUE THREAD

**Issue by pirklbauer31** [iotempire/iotempower#4]
When trying to integrate a RGB LED module via MQTT controlling the LED leads to weird behaviour (interface flashing, color picking not working correctly, etc.)

The LED is configured in my configuration.yaml file in home assistant like this:
````
light:
  - platform: mqtt
    name: "L3 Light RGB"
    state_topic: "node2/rgb1"
    command_topic: "node2/rgb1/set"
    brightness_state_topic: "node2/rgb1/brightness"
    brightness_command_topic: "node2/rgb1/brightness/set"
    rgb_state_topic: "node2/rgb1/rgb"
    rgb_command_topic: "node2/rgb1/rgb/set"
    payload_on: "on"
    payload_off: "off"
    optimistic: false
    on_command_type: 'first'
`````

The problem might be the Node not sending status updates correctly.
